CREATE DATABASE dot11monitor;
\c dot11monitor

CREATE USER dot11viewer WITH PASSWORD 'dot11password';

CREATE SCHEMA IF NOT EXISTS private;

GRANT CONNECT ON DATABASE dot11monitor TO dot11viewer;

ALTER DEFAULT PRIVILEGES FOR USER dot11viewer
REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR USER dot11viewer IN SCHEMA private
GRANT SELECT ON TABLES TO dot11viewer;
