CREATE DATABASE dot11monitor;

CREATE USER dot11viewer WITH PASSWORD 'dot11password';
CREATE USER dot11admin WITH PASSWORD 'dot11password';
GRANT CONNECT ON DATABASE dot11monitor TO dot11admin;
GRANT CONNECT ON DATABASE dot11monitor TO dot11viewer;
\c dot11monitor

CREATE SCHEMA private;

REVOKE ALL ON SCHEMA information_schema FROM public ;
REVOKE ALL ON SCHEMA public FROM public ;

GRANT USAGE ON SCHEMA public TO dot11viewer;

ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR USER dot11admin GRANT SELECT ON TABLES TO dot11viewer;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO dot11viewer;
