FROM ubuntu:16.04

RUN apt-get update && \
  apt-get install -y software-properties-common && \
  add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv && \
    rm -rf /var/lib/apt/lists/*

RUN python3.6 -m pip install pip --upgrade
COPY ./Docker/requirements.api.txt /
RUN python3.6 -m pip install -r /requirements.api.txt

COPY ./Api /Api
