"""empty message

Revision ID: 1b69acc85d3c
Revises: 
Create Date: 2019-11-22 00:52:24.173603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b69acc85d3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aps',
    sa.Column('ap_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('essid', sa.String(length=256), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('privacy', sa.String(length=8), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('ap_mac', 'workspace'),
    sa.UniqueConstraint('ap_mac')
    )
    op.create_index(op.f('ix_aps_channel'), 'aps', ['channel'], unique=False)
    op.create_index(op.f('ix_aps_essid'), 'aps', ['essid'], unique=False)
    op.create_index(op.f('ix_aps_privacy'), 'aps', ['privacy'], unique=False)
    op.create_table('clients',
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('mac_vendor', sa.String(length=256), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('client_mac', 'workspace'),
    sa.UniqueConstraint('client_mac')
    )
    op.create_table('authorisations',
    sa.Column('ap_mac', sa.String(length=32), nullable=False),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ap_mac'], ['aps.ap_mac'], ),
    sa.ForeignKeyConstraint(['client_mac'], ['clients.client_mac'], ),
    sa.PrimaryKeyConstraint('ap_mac', 'client_mac', 'workspace')
    )
    op.create_table('data_transfer',
    sa.Column('ap_mac', sa.String(length=32), nullable=False),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ap_mac'], ['aps.ap_mac'], ),
    sa.ForeignKeyConstraint(['client_mac'], ['clients.client_mac'], ),
    sa.PrimaryKeyConstraint('ap_mac', 'client_mac', 'workspace')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_transfer')
    op.drop_table('authorisations')
    op.drop_table('clients')
    op.drop_index(op.f('ix_aps_privacy'), table_name='aps')
    op.drop_index(op.f('ix_aps_essid'), table_name='aps')
    op.drop_index(op.f('ix_aps_channel'), table_name='aps')
    op.drop_table('aps')
    # ### end Alembic commands ###
