"""empty message

Revision ID: 2f1a3b0748e9
Revises: 
Create Date: 2019-11-28 00:11:32.545226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1a3b0748e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ap_mac', sa.String(length=32), nullable=True),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('mac_vendor', sa.String(length=256), nullable=True),
    sa.Column('essid', sa.String(length=256), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('privacy', sa.String(length=8), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id', 'workspace')
    )
    op.create_index(op.f('ix_ap_ap_mac'), 'ap', ['ap_mac'], unique=True)
    op.create_index(op.f('ix_ap_channel'), 'ap', ['channel'], unique=False)
    op.create_index(op.f('ix_ap_essid'), 'ap', ['essid'], unique=False)
    op.create_index(op.f('ix_ap_privacy'), 'ap', ['privacy'], unique=False)
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_mac', sa.String(length=32), nullable=True),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('mac_vendor', sa.String(length=256), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id', 'workspace')
    )
    op.create_index(op.f('ix_client_client_mac'), 'client', ['client_mac'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_collector', sa.Boolean(), nullable=True),
    sa.Column('is_viewer', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ap_mac', sa.String(length=32), nullable=True),
    sa.Column('client_mac', sa.String(length=32), nullable=True),
    sa.Column('workspace', sa.String(length=256), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ap_mac'], ['ap.ap_mac'], ),
    sa.ForeignKeyConstraint(['client_mac'], ['client.client_mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_ap_mac'), 'auth', ['ap_mac'], unique=False)
    op.create_index(op.f('ix_auth_client_mac'), 'auth', ['client_mac'], unique=False)
    op.create_index(op.f('ix_auth_workspace'), 'auth', ['workspace'], unique=False)
    op.create_table('data_transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ap_mac', sa.String(length=32), nullable=True),
    sa.Column('client_mac', sa.String(length=32), nullable=True),
    sa.Column('workspace', sa.String(length=256), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ap_mac'], ['ap.ap_mac'], ),
    sa.ForeignKeyConstraint(['client_mac'], ['client.client_mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_transfer_ap_mac'), 'data_transfer', ['ap_mac'], unique=False)
    op.create_index(op.f('ix_data_transfer_client_mac'), 'data_transfer', ['client_mac'], unique=False)
    op.create_index(op.f('ix_data_transfer_workspace'), 'data_transfer', ['workspace'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_transfer_workspace'), table_name='data_transfer')
    op.drop_index(op.f('ix_data_transfer_client_mac'), table_name='data_transfer')
    op.drop_index(op.f('ix_data_transfer_ap_mac'), table_name='data_transfer')
    op.drop_table('data_transfer')
    op.drop_index(op.f('ix_auth_workspace'), table_name='auth')
    op.drop_index(op.f('ix_auth_client_mac'), table_name='auth')
    op.drop_index(op.f('ix_auth_ap_mac'), table_name='auth')
    op.drop_table('auth')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_client_client_mac'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_ap_privacy'), table_name='ap')
    op.drop_index(op.f('ix_ap_essid'), table_name='ap')
    op.drop_index(op.f('ix_ap_channel'), table_name='ap')
    op.drop_index(op.f('ix_ap_ap_mac'), table_name='ap')
    op.drop_table('ap')
    # ### end Alembic commands ###
