"""empty message

Revision ID: 419898c4255a
Revises: 
Create Date: 2019-11-25 12:06:37.886710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419898c4255a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap',
    sa.Column('ap_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('essid', sa.String(length=256), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('privacy', sa.String(length=8), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('ap_mac', 'workspace'),
    sa.UniqueConstraint('ap_mac')
    )
    op.create_index(op.f('ix_ap_channel'), 'ap', ['channel'], unique=False)
    op.create_index(op.f('ix_ap_essid'), 'ap', ['essid'], unique=False)
    op.create_index(op.f('ix_ap_privacy'), 'ap', ['privacy'], unique=False)
    op.create_table('client',
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('mac_vendor', sa.String(length=256), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('client_mac', 'workspace'),
    sa.UniqueConstraint('client_mac')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_collector', sa.Boolean(), nullable=True),
    sa.Column('is_viewer', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth',
    sa.Column('ap_mac', sa.String(length=32), nullable=False),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ap_mac'], ['ap.ap_mac'], ),
    sa.ForeignKeyConstraint(['client_mac'], ['client.client_mac'], ),
    sa.PrimaryKeyConstraint('ap_mac', 'client_mac', 'workspace')
    )
    op.create_table('data_transfer',
    sa.Column('ap_mac', sa.String(length=32), nullable=False),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=256), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ap_mac'], ['ap.ap_mac'], ),
    sa.ForeignKeyConstraint(['client_mac'], ['client.client_mac'], ),
    sa.PrimaryKeyConstraint('ap_mac', 'client_mac', 'workspace')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_transfer')
    op.drop_table('auth')
    op.drop_table('user')
    op.drop_table('client')
    op.drop_index(op.f('ix_ap_privacy'), table_name='ap')
    op.drop_index(op.f('ix_ap_essid'), table_name='ap')
    op.drop_index(op.f('ix_ap_channel'), table_name='ap')
    op.drop_table('ap')
    # ### end Alembic commands ###
